version: "3"
services:
    db:
        container_name: database-social-bias
        image: postgres:13.2-alpine
        restart: always
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            PGDATA: /var/lib/postgresql/data
        volumes:
            - db-data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
    app:
        container_name: app-social-bias
        build:
            context: app
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        depends_on:
            - db
        environment:
            - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@localhost:5432/${POSTGRES_DB}


volumes:
    db-data: